name: Build Example Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-repo:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install Dependencies
      run: |
        pip install cookiecutter
        pip install --upgrade tox
    - name: Generate Repo
      run: |
        cookiecutter . --no-input
        rm -Rf packagename/.github/workflows/build_package.yml
    - name: Install Generated Repo Dependencies
      run: |
        cd packagename
        git init
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add .
        git commit -m "first commit"
        git tag -a v1.0 -m "fake version 1.0"
        pip install -e .[all]
    - name: Run package tox Tests
      run: |
        tox
    - name: Run package generated Repo Lint
      run: |
        cd packagename
        tox -e codestyle
    - name: Run package generate Docs
      run: |
        tox -e build_docs