name: Deploy Example Package to branch

on:
  push:
    branches:
      - main

jobs:
  build-repo:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        pip install cookiecutter
        pip install --upgrade tox
    - name: Generate Repo
      run: |
        cookiecutter . --no-input
    - name: Publish Repo
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: main # The branch the action should deploy from.
        BRANCH: 'example-build' # The branch the action should deploy to.
        FOLDER: packagename/ # The folder the action should deploy
        CLEAN: true
